services:
  app:
    build: .
    container_name: app-1
    runtime: runc
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    depends_on:
      - vllm
    environment:
      - VLLM_ENDPOINT=http://vllm:8000/v1
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
      - USE_MOCKS=0
    networks:
      - spotify_net

  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm-1
    runtime: runc
    ports:
      - "8000:8000"
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    command:
      - --model
      - google/gemma-3-1b-it

networks:
  spotify_net:
    driver: bridge
